#!/usr/bin/env bash

alias mq='hg -R $(hg root)/.hg/patches'

pull_everything() {
    for repo in $( ls -1 ); do
        if [[ -d $repo && -d $repo/.hg ]]; then
            echo "Pulling" $repo
            hg -R $repo pull -u
            echo
        fi
    done
}

bitb() {
    local P="$(grep 'bitbucket.org' `hg root`/.hg/hgrc 2>/dev/null | head -1)"
    local URL="$(echo $P | sed -e's|.*\(bitbucket.org.*\)|http://\1|')"
    [[ -n $URL ]] && open $URL || echo "No BitBucket path found!"
}